package org.btcprivate.wallets.fullnode;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.btcprivate.wallets.fullnode.daemon.BTCPClientCaller;
import org.btcprivate.wallets.fullnode.ui.BTCPWalletUI;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.assertNotNull;

public class BTCPWalletUITest {
    @Test
    public void testAppHasAGreeting() throws InterruptedException, BTCPClientCaller.WalletCallException, IOException {
        BTCPWalletUI classUnderTest = null;
        classUnderTest = new BTCPWalletUI(null,"BTCP Wallet TEST");
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
